<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>CrownConquest.Data</RootNamespace>
    <AssemblyName>CrownConquest.Data</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrownConquest.Domain\CrownConquest.Domain.csproj" />
  </ItemGroup>

</Project>
